spring.application.name=demo

# Connexion H2 en mémoire (les données disparaissent au redémarrage)
spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console web H2 pour visualiser la BDD dans le navigateur
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Génère automatiquement les tables à partir des entités Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true